name: Continuous Integration

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
      - name: Standalone Angular Build
        run: npm run sa-build --if-present
        env:
          CI: true
      - name: Unit Test - Standalone
        run: npm run ci-test --if-present
        env:
          CI: true
      - name: Update Web Drivers
        run: npx webdriver-manager update
      - name: End 2 End Test - Standalone
        run: npm run ci-sa-e2e --if-present
        env:
          CI: true
      - name: Archive Test results
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: reports
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-reports
          path: coverage
